name: Build & Test

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.9.13' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Display Python version
        run: python --version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libvpx-dev \
            libevent-dev \
            libopus-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libharfbuzz-dev \
            libhyphen-dev \
            libflite1 \
            libgles2-mesa-dev \
            libx264-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-asyncio
          python -m pip install -r requirements.txt
          playwright install

      - name: Run tests
        run: |
          pytest -v --full-trace --durations 10 --timeout=1200 test.py
